# Generated by Django 5.2.11 on 2026-02-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('roll_no', models.IntegerField()),
                ('email', models.IntegerField()),
                ('course', models.CharField(max_length=40)),
            ],
        ),
    ]
